identifier-prefix: ogc.contrib.stac

name: OGC Building Blocks for STAC
abstract: These [Building Blocks](https://ogcincubator.github.io/bblocks-docs/) provide a validation and documentation wrapper over STAC and extension schemas, and aid in transparent re-use of STAC elements
description: |
  Allows for validation and testing of STAC examples.
  
  **STAC extends OGC API Records** (i.e. Records is designed to be compatible with the prior STAC mode) - this packaging supports validation of STAC extensions against underlying Records, Features and Common elements.
  
  Supports definition and testing of transformations to/from STAC from other formats.
  
  Implementers can fork this repository and add additional examples in the `tests/` directory of each Building Block and run validation processes locally.
  
  Provides a framework for documentation and testing of additional extensions.

imports:
  - default
  - https://ogcincubator.github.io/cross-domain-model
  - https://ogcincubator.github.io/bblock-prov-schema
  - https://ogcincubator.github.io/geodcat-ogcapi-records

# this config means ontology contents are automatically pushed to the test environment

sparql:
  push: https://defs-dev.opengis.net/fuseki/data
  # graph: https://my.bblocks.example.com/  # SPARQL Graph where data will be uploaded
                                            #  if left empty, the base URL for the publication will be used
  query: https://defs-dev.opengis.net/fuseki/sparql

